apiVersion: apps/v1
kind: Deployment
metadata:
  name: topics
spec:
  selector:
    matchLabels:
      app: topics
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: topics
    spec:
      containers:
        - name: topics
          image: suriyajaboon/topics:0.1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 2
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 100Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 500m