apiVersion: apps/v1
kind: Deployment
metadata:
  name: offset
spec:
  selector:
    matchLabels:
      app: offset
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: offset
    spec:
      containers:
        - name: offset
          image: suriyajaboon/offset:0.2
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 1323
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 1323
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 2
          ports:
            - containerPort: 1323
          resources:
            requests:
              memory: 100Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 500m